version: '4.2'

services:
  # --- SERVIZIO DATABASE ---
  db:
    image: mysql:8.0
    container_name: studenthub-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studenthub_db
    ports:
      - "3307:3306"
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

  # --- SERVIZIO BACKEND ---
  backend:
    build: ./backend
    container_name: studenthub-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      # Aspetta che il DB sia "healthy" prima di partire
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=studenthub_db
      - DB_PORT=3306
      - PORT=3000
      - JWT_SECRET=e1d5b0ac408961e36a35c0a11476e1a9b1bf75a7737d238e3d2aa2ba4efa8bdfb852ad4e34427096724264257ccf12b3e040277af230061c790dd02d0b17984f

  # --- SERVIZIO FRONTEND ---
  frontend:
    build: ./frontend
    container_name: studenthub-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: